apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendApplication
  labels:
    app: frontendApplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendApplication-java
  template:
    metadata:
      labels:
        app: frontendApplication-java
    spec:
      containers:
      - name: frontendApplication-javaserver
        image: madhublue01/frontendApplication:latest
        ports:
        - containerPort: 8083
        
        
---



apiVersion: v1
kind: Service
metadata:
  name: frontendApplication-java-service
spec:
  selector:
    app: frontendApplication-java
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8083
    nodePort: 30082
